## NumPy

##### Three Ways to Import

In [3]:
import numpy as np
from numpy import sqrt
import numpy

##### Three ways to call methods from libraries

In [11]:
np.sqrt(4)
sqrt(4)
numpy.sqrt(4)

2.0

##### Creating Vector Arrays

In [13]:
vec = np.array([3,4,5])
vec2 = np.array((3,4,5))

In [15]:
# Print the type
print(type(vec))
print(type(vec2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
# Check the shape
print(vec.shape)
print(vec2.shape)

(3,)
(3,)


In [18]:
# Notice the shape is (3,). This is the case so that when we begin
# to add columns to create a matrix, we can call shape on that matrix
# as well.

In [37]:
# Default type is int64, but can cast the values as particular type
vec_demo = np.array([4,5,6], np.float)
print(vec_demo)

[ 4.  5.  6.]


##### Reshape

In [21]:
# We can reshape arrays into the dimensions we want for some
# numeric operation
row_vec = np.array([7,2,9]).reshape(1,3)
col_vec = np.array([3,1,7,4]).reshape(4,1)
print(row_vec.shape)
print(col_vec.shape)

(1, 3)
(4, 1)


In [22]:
row_vec

array([[7, 2, 9]])

In [23]:
col_vec

array([[3],
       [1],
       [7],
       [4]])

##### Creating Matrix Arrays

In [24]:
mat = np.array([[2,0], [5,1], [7,-3]])

In [25]:
mat

array([[ 2,  0],
       [ 5,  1],
       [ 7, -3]])

In [26]:
mat.shape

(3, 2)

In [27]:
# We can also reshape matrices
mat2 = mat.reshape(2,3)

In [28]:
mat2

array([[ 2,  0,  5],
       [ 1,  7, -3]])

In [31]:
# Now the stupid easy matrix transposition with NumPy
mat_T = mat.T

In [32]:
mat_T

array([[ 2,  5,  7],
       [ 0,  1, -3]])

In [33]:
# Notice that reshape and transpose do NOT produce the same results

##### Indexing NumPy Arrays

In [40]:
# Since our matrix has 3 rows and 2 columns, we can index like so
mat

array([[ 2,  0],
       [ 5,  1],
       [ 7, -3]])

In [38]:
mat.shape

(3, 2)

In [39]:
# Notice the 0 indexing
mat[2, 1]

-3

In [42]:
# Let's create a matrix

# I'm calling np.arrange which will give me a list of numbers
# from 0 to 99. Then I'm reshaping so that I have 10 rows and 
# 10 columns
M = np.arange(100).reshape(10,10)

In [43]:
M

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [44]:
# Let's say I want a slice of rows
M[2:5]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
# Let's say I want a slice of columns
M[:, 4:8]

array([[ 4,  5,  6,  7],
       [14, 15, 16, 17],
       [24, 25, 26, 27],
       [34, 35, 36, 37],
       [44, 45, 46, 47],
       [54, 55, 56, 57],
       [64, 65, 66, 67],
       [74, 75, 76, 77],
       [84, 85, 86, 87],
       [94, 95, 96, 97]])

In [46]:
# Let's slice into both rows and columns
# Rows 1-4 values between columns 3 and 5
M[1:5, 3:6]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35],
       [43, 44, 45]])

##### Modifying Arrays

In [47]:
# Remember that arrays are mutable? Let's mutate them.
M

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
# Let's change row 2 values to 100
M[2:3] = 100
M

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [51]:
# For all the row values in between columns 4 and 7, let's subtract 200
M[:, 4:7] += -200
M

array([[   0,    1,    2,    3, -396, -395, -394,    7,    8,    9],
       [  10,   11,   12,   13, -386, -385, -384,   17,   18,   19],
       [ 100,  100,  100,  100, -300, -300, -300,  100,  100,  100],
       [  30,   31,   32,   33, -366, -365, -364,   37,   38,   39],
       [  40,   41,   42,   43, -356, -355, -354,   47,   48,   49],
       [  50,   51,   52,   53, -346, -345, -344,   57,   58,   59],
       [  60,   61,   62,   63, -336, -335, -334,   67,   68,   69],
       [  70,   71,   72,   73, -326, -325, -324,   77,   78,   79],
       [  80,   81,   82,   83, -316, -315, -314,   87,   88,   89],
       [  90,   91,   92,   93, -306, -305, -304,   97,   98,   99]])

In [52]:
# Let's replace a slice of our matrix with a new array
replacement = np.array([[1,2], [3,4]])
M[8:10, 1:3] = replacement
M

array([[   0,    1,    2,    3, -396, -395, -394,    7,    8,    9],
       [  10,   11,   12,   13, -386, -385, -384,   17,   18,   19],
       [ 100,  100,  100,  100, -300, -300, -300,  100,  100,  100],
       [  30,   31,   32,   33, -366, -365, -364,   37,   38,   39],
       [  40,   41,   42,   43, -356, -355, -354,   47,   48,   49],
       [  50,   51,   52,   53, -346, -345, -344,   57,   58,   59],
       [  60,   61,   62,   63, -336, -335, -334,   67,   68,   69],
       [  70,   71,   72,   73, -326, -325, -324,   77,   78,   79],
       [  80,    1,    2,   83, -316, -315, -314,   87,   88,   89],
       [  90,    3,    4,   93, -306, -305, -304,   97,   98,   99]])

##### Class Question Answers / Demo

In [85]:
# Python Lists can hold any data type, NumPy arrays can only hold int or float
test = np.array([1,2,3,'dog'])

In [81]:
# This will create a 10x10 matrix with values from 0 to 100
m = np.arange(100).reshape(10,10)
# This will multiply all the row values between columns 2 and 5 by 4
m[:, 2:5] *= 4

In [83]:
# What is wrong with this code? The shapes of the replacement array
# and the matrix slice you're trying to replace do not match.
replace = np.array([[2,3,5,6], [4,3,6,5], [4,3,1,2]])
m[3:5, 0:4] = replace

##### Boolean Indexing

In [109]:
my_list = [2, 3, 5, 4, 6, 8, 10]
for num in my_list:
    print(num % 2 == 0)
    
    
# Notice that this is doing almost the exact same thing as the code above
# but is instead returning an array of boolean values with the same shape
# as the array you start with

my_arr = np.array([2, 3, 5, 4, 6, 8, 10])
test = my_arr % 2 == 0
print(test)

True
False
False
True
True
True
True
[ True False False  True  True  True  True]


In [110]:
my_arr.shape

(7,)

In [111]:
test.shape

(7,)

In [112]:
# I can find the values I want to change with a boolean mask
# and change those values
# In the following code, any values that evaluate to True will be
# changed

my_arr[my_arr % 2 == 0] = -12



In [114]:
my_arr

array([-12,   3,   5, -12, -12, -12, -12])

In [115]:
def elements_greater_than_mean(arr):
    mask = [arr > np.mean(arr)]
    
    return arr[mask]

In [117]:
elements_greater_than_mean(np.array([0.2, 0.8, 0.3, 0.6]))

array([ 0.8,  0.6])