In [2]:
import numpy as np

##### Scalar Operations with Vectors

In [15]:
vec = np.array([3,5,7])
vec_5x = 5 * vec
print(vec, vec_5x)

[3 5 7] [15 25 35]


##### Elementwise Operations with Vectors

In [35]:
# Elementwise operations of vectors
y = np.array([1,2,3])
x = np.array([2,3,4])

y_add_x = y + x
y_subtract_x = y - x
y_divide_x = y / x

# Also called Hadamard Product (when it outputs a vector, not dot product)
y_multiply_x = y * x

In [36]:
print(y_add_x)
print(y_subtract_x)
print(y_divide_x)
print(y_multiply_x)

[3 5 7]
[-1 -1 -1]
[ 0.5         0.66666667  0.75      ]
[ 2  6 12]


##### Vector Dot Product

In [8]:
# Dot product of vectors
y = np.array([1,2,3])
x = np.array([2,3,4])
y_dot_x = np.dot(y,x)

In [9]:
print(y_dot_x)

20


##### Scalar Operations with Matrices

In [16]:
# Make matrix in NumPy
a = np.array([
 [1,2,3],
 [4,5,6]
])

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# Check the dimensions of your matrix
print(a.shape)

(2, 3)


In [20]:
# Scalar Operations with Matrices
a_add_1 = a + 1
a_sub_1 = a - 1
a_divide_1 = a / 1
a_multiply_1 = a * 1

In [21]:
print(a_add_1)
print(a_sub_1)
print(a_divide_1)
print(a_multiply_1)

[[2 3 4]
 [5 6 7]]
[[0 1 2]
 [3 4 5]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[[1 2 3]
 [4 5 6]]


##### Elementwise Operations with Matrices

In [22]:
# Elementwise Operations with Matrices
a = np.array([
 [1,2],
 [3,4]])
b = np.array([
 [1,2],
 [3,4]])

a_add_b = a + b
a_sub_b = a - b
# Hadamard product of matrices (not dot product)
a_multiply_b = a * b

In [23]:
print(a_add_b)
print('---------')
print(a_sub_b)
print('---------')
print(a_multiply_b)

[[2 4]
 [6 8]]
---------
[[0 0]
 [0 0]]
---------
[[ 1  4]
 [ 9 16]]


##### Matrix Transposition and Dot Product

In [24]:
# Matrix Transposition
a = np.array([
   [1, 2],
   [3, 4]])

print(a)
print('---------')
print(a.T)

[[1 2]
 [3 4]]
---------
[[1 3]
 [2 4]]


In [26]:
# Matrix Multiplication 
# Remember: num columns from 1st matrix must == num rows from 2nd
# Remember: resulting matrix will have shape (rows of 1st, cols of 2nd)
a = np.array([
 [1, 2]
 ])
b = np.array([
 [3, 4],
 [5, 6]
 ])

# Multiply
mm = np.dot(a,b)

In [27]:
print(a)
print(a.shape)
print('---------')
print(b)
print(b.shape)
print('---------')
print(mm)
print(mm.shape)

[[1 2]]
(1, 2)
---------
[[3 4]
 [5 6]]
(2, 2)
---------
[[13 16]]
(1, 2)


In [50]:
# What happens if you try to dot product matrices with the wrong shape?
a = np.array([
 [1, 2]
 ])
b_wrong_dim = np.array([
 [3, 4],
 [5, 6],
    [7,5]
 ])

In [51]:
print(a.shape)
print(b_wrong_dim.shape)

(1, 2)
(3, 2)


In [52]:
# Fail at dot product
# You will get this error more than any other error. I promise.
mm_fail = np.dot(a,b_wrong_dim)

ValueError: shapes (1,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [56]:
# But, you can still elementwise multiply them, which can cause some bugs that are hard to find.
mm_hadamard = a * b_wrong_dim
print(mm_hadamard)

[[ 3  8]
 [ 5 12]
 [ 7 10]]


In [53]:
# However, if you have a matrix is the wrong dim, you can transpose it to fit the other matrix if you can get the cols from first to match rows from second
print(a.shape)
print(b_wrong_dim.shape)

(1, 2)
(3, 2)


In [54]:
mm_dot_bT = np.dot(a,b_wrong_dim.T)

In [55]:
print(mm_dot_bT)

[[11 17 17]]


In [39]:
# Just to visualize the difference between elementwise
# multiplication and dot product of matrices
mat1 = np.array([[1,2,3],[4,5,6],[1,2,3]])
mat2 = np.array([[1,2,3],[4,5,6],[1,2,3]])
print(mat1.shape)
print(mat2.shape)

(3, 3)
(3, 3)


In [40]:
elementwise = mat1 * mat2
dotproduct = np.dot(mat1, mat2)
print(mat1)
print('---------')
print(mat2)

[[1 2 3]
 [4 5 6]
 [1 2 3]]
---------
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [41]:
print(elementwise)
print('---------')
print(dotproduct)

[[ 1  4  9]
 [16 25 36]
 [ 1  4  9]]
---------
[[12 18 24]
 [30 45 60]
 [12 18 24]]


##### Matrix Rank

In [42]:
matrix = np.array([[1,2,3],[2,14,34],[2,4,6],[1,1,1]])

In [44]:
matrix_rank = np.linalg.matrix_rank(matrix)

In [45]:
matrix_rank

3