In [1]:
import numpy as np

In [2]:
xray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
xray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
xray.shape

(3, 3)

In [7]:
row = np.array([[1, 2, 3]])
print(row)
print(row.shape)

[[1 2 3]]
(1, 3)


In [9]:
cols = np.array([[1], [2], [3]])
print(cols)
print(cols.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [10]:
range_arr = np.arange(0, 100, 2)
range_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [13]:
lin_arr = np.linspace(0, 100, 7)
print(lin_arr)

[  0.          16.66666667  33.33333333  50.          66.66666667
  83.33333333 100.        ]


In [14]:
linspace_arr = np.linspace(0., 100., 4)

In [15]:
linspace_arr.shape

(4,)

In [16]:
linspace_arr = np.linspace(0., 100., 4)

In [17]:
linspace_arr

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [18]:
linspace_arr.shape

(4,)

In [19]:
linspace_arr.reshape(-1, 1)

array([[  0.        ],
       [ 33.33333333],
       [ 66.66666667],
       [100.        ]])

In [20]:
linspace_arr.reshape(1, -1)

array([[  0.        ,  33.33333333,  66.66666667, 100.        ]])

In [22]:
X = np.array([[3, 5], [5, 7]])
Y = np.array([[7, 5], [5, 3]])
X + Y

array([[10, 10],
       [10, 10]])

In [23]:
X + 4

array([[ 7,  9],
       [ 9, 11]])

In [24]:
X = np.arange(0, 20, 1).reshape(5, 4)

In [26]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
X[1, 1]

5

In [30]:
X[:, 3]

array([ 3,  7, 11, 15, 19])

In [31]:
X[:, 3].reshape(-1, 1)

array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])

In [32]:
X.sum()

190

In [33]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [36]:
X.sum(axis=0).shape

(4,)

In [37]:
X.sum(axis=1).shape

(5,)

In [38]:
X.cumprod(axis=0)

array([[    0,     1,     2,     3],
       [    0,     5,    12,    21],
       [    0,    45,   120,   231],
       [    0,   585,  1680,  3465],
       [    0,  9945, 30240, 65835]])

In [39]:
X.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36],
       [40, 45, 50, 55]])

In [40]:
z = np.arange(2, 30, 2)

In [42]:
z

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [43]:
print(np.where(z > 3))

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]),)


In [44]:
vec = np.array([3,5,7])

In [45]:
vec

array([3, 5, 7])

In [46]:
mat = np.array([[3,2],[7,4],[9,1]])

In [47]:
mat

array([[3, 2],
       [7, 4],
       [9, 1]])

In [48]:
vec2 = np.array([2, 3, 4])

In [49]:
mat2 = np.array([[1, 2], [2, 3], [3, 4]])

In [50]:
vec.dot(vec2)

49

In [51]:
mat3 = np.array([[2, -1, 3, 0], [-2, 0, -1, 4]])

In [52]:
mat.dot(mat3)

array([[ 2, -3,  7,  8],
       [ 6, -7, 17, 16],
       [16, -9, 26,  4]])

In [53]:
mat3

array([[ 2, -1,  3,  0],
       [-2,  0, -1,  4]])

In [54]:
mat3.shape

(2, 4)

In [55]:
mat3.T

array([[ 2, -2],
       [-1,  0],
       [ 3, -1],
       [ 0,  4]])